### ISSUE TITLE
How to create a preview → read-me

### ISSUE THREAD

**Issue by katkolouchova** [faktaoklimatu/web-core#144]
It would be nice to add the process of creating a preview into Read me.

**Comment by mukrop** [comment]
Do you find it necessary specifically within the `Readme` file? In the conventions section, the `Readme` links to [Notion workflow description](https://www.notion.so/faktaoklimatu/Workflow-GitHub-4c5b294731dc4f9a8b2203daefcff432) where the comment on branch naming is present.

**Comment by katkolouchova** [comment]
The Notion description is good enough, I must have overlooked it. Thanks!
