### ISSUE TITLE
Optimizing CI runs

### ISSUE THREAD

**Issue by mukrop** [faktaoklimatu/web-core#203]
Aim: Spend fewer Travis credits as multiple runs of the CI are redundant (especially for editors making changes one by one via the web interface). Yet we still want to keep the GitHub build checks preventing merge in unbuildable states.

Possibilities to run CI less frequently (that is, not on each push):
* Only build commits with certain tags. Unusable as this would be too complicated for multiple content editors.
* Manual ways to trigger a build check from GitHub seems non-existent at this time (although, for example, Jenkins seems to have this functionality).
* There is a way to skip a build by including the command to skip the build in the commit message. See [Travis documentation](https://docs.travis-ci.com/user/customizing-the-build/#skipping-a-build). Though this would probably not help us much as the content editors doing changes one by one would need to be taught to do this.
* Travis allows for build conditions on multiple things ([documentation here](https://docs.travis-ci.com/user/conditions-v1)). It could be possible to establish a keyword in the commit message to ask for build. We'd need to teach this to the content editors (that is possible).

All in all, any change would have to include training all our non-IT stuff to trigger a build when they need it. Although this can be done, I think it's not worth the trouble since Travis so far happily grants us free OSS credits.

Do you agree, @jankrcal?

**Comment by jankrcal** [comment]
Thanks for the research! Yes, I agree that the solution is too costly, given non-solution is almost free :)

**Comment by jankrcal** [comment]
I'd close the issue, hoping that I'll find it again once we need to revisit the decision.
