### ISSUE TITLE
Double occurence of the same product in the Related infographics and studies section

### ISSUE THREAD

**Issue by katkolouchova** [faktaoklimatu/web-core#206]
See e.g. https://faktaoklimatu.cz/studie/2021-reserse-zavazky-statu
<img width="1185" alt="image" src="https://user-images.githubusercontent.com/49321752/200317653-94a531d8-44ee-4786-a15e-4b57ccdab826.png">

Or https://faktaoklimatu.cz/infografiky/emisni-zavazky
<img width="1151" alt="image" src="https://user-images.githubusercontent.com/49321752/200317920-c972ebc8-2f0b-4196-a711-a0ea1415091f.png">

**Comment by jankrcal** [comment]
Ah, good catch, will fix soon.
