### ISSUE TITLE
Vyjasnit instrukce a opravit Docker (rootless v Ubuntu nefunguje)

### ISSUE THREAD

**Issue by jankrcal** [faktaoklimatu/web-core#21]
Pokusil jsem se zprovoznit build přes kontejnery podle README.md. Zjistil jsem, že nemám k dispozici podman a že nejspíše mám k dispozici Docker.

Instrukce zmiňují, že pro "použití s Dockerem je téměř totožné (viz níže).", ale žádné níže vyjadřující se o Dockeru jsem nenašel. Přehlížím něco?

Konkrétně mě zajímá: co potřebuju lokálně změnit / nastavit, abych úspěšně mohl fungovat s Dockerem?

**Comment by jankrcal** [comment]
Omlouvám se za dlouhou prodlevu. Byla způsobená tím, že se mi s tím moc nechce trávit čas. 
Mám totiž divnej setup, tak mám pocit, že moje případné utrpení by nikomu nepomohlo.

Kdyby ti to Martine přišlo důležitý, můžu na to kouknout.

**Comment by crysman** [comment]
já jsem přešel na standard system build, je to spolehlivé, a prerekvizit je málo, takže s tím není trabl

**Comment by mukrop** [comment]
Ja v tom az taku prioritu nevidim. Container build ma na starosti (a najviac pouziva) @mgrabovsky. A ak mas, @jankrcal, dojem, ze pre teba to zasadne nie je a nejako to rozchodene mas, tak by som tento issue navrhol zatvorit.

**Comment by jankrcal** [comment]
Souhlasim, zaviram.
