### ISSUE TITLE
Automatic image scaling

### ISSUE THREAD

**Issue by mukrop** [faktaoklimatu/web-core#28]
Find out if we need to serve differently scaled images for different devices (4K retina monitor vs. mobile phone). Especially relevant for explainer cover photos, but could be retrospectively applied to infographics as well.

**Comment by jankrcal** [comment]
To me, for explainers this is a *must have*.

We use the _same_ cover photos in preview boxes (the photos can easily have 1-2 MB).
This is especially blocking for the 'search' feature where again, we use the cover photos for previews.

Maybe it's worth splitting off an issue about generating preview versions of cover photos from this issue?
(which is mainly about serving the right version of the image for the actual page, based on resolution)

Before we agree on that: did we have any raster image rescaling dependency before using Inkscape? As Inkscape cannot resize jpgs, we need to use another tool so I am wondering if we had some tool working well before (like image magick).

**Comment by mukrop** [comment]
Yes, agreed.
We did not have any raster image manipulation tool AFAIK. ImageMagic is
server classic, but I've heard a lot of moaning at is as well. Give a brief
moment (or a question to friends) on alternatives, but going with it is
probably OK with me. If we decide to change it in the future, it should not
be problematic.

>

**Comment by jankrcal** [comment]
Split off. Scoping this issue back down to _serving_ the right size of images for each device on the infographic / explainer / ... page.

**Comment by jankrcal** [comment]
By the way, this is likely the simplest tool to use for this issue (as with most modern web tools, I was not aware of it):
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture

**Comment by mukrop** [comment]
That seems to be a very good (and modern) solution :-).

>
