### ISSUE TITLE
Switch title and text of preview-box?

### ISSUE THREAD

**Issue by mukrop** [faktaoklimatu/web-core#55]
I'm considering reordering the preview box to

1. Title
2. Description text
3. Preview image

That is, move the text from under the image above it. I find the title right above the image (that often has a title of its own) not aesthetically pleasing.
An example preview box can be seen at https://faktaoklimatu.cz/infografiky/emise-fosilni-paliva

Any opinisons? @jankrcal @mgrabovsky

**Comment by mgrabovsky** [comment]
> I find the title right above the image (that often has a title of its own) not aesthetically pleasing.

I agree. This is especially awkward when the title of the box is the same as the title of the linked graphic. (Not sure if that is the case in any of the instances at the moment, but I recall struggling with that before.)
