### ISSUE TITLE
Fix search on Safari

### ISSUE THREAD

**Issue by jankrcal** [faktaoklimatu/web-core#59]
On Safari, clicking on a search result closes the search results box instead of navigating to the result.
Navigating to the result with keyboard works fine.

**Comment by mukrop** [comment]
Hm, that sounds as quite a serious bug (for Safari). Are you the only one Mac-based dev of ours? Matej, I think, is Linux-based and I have no idea about Fil.

**Comment by jankrcal** [comment]
I use Mac but I, for obvious reasons, use Chrome.

This was reported by @marek-krcal.

**Comment by crysman** [comment]
issue confirmed on my friend's mobile (Apple, Safari) - page not being opened upon touch on search result item

**Comment by mgrabovsky** [comment]
Is this on mobile-only or desktop as well?

**Comment by mgrabovsky** [comment]
This might be an artifact of the way that losing focus is handled. The modal is closed when the search box loses focus (by click/touch or some keystroke).

I have encountered a (most likely) related problem when switching keyboard layout while the search box is focused. Pressing Super+Space (the default shortcut to switch layouts in GNOME) with the search input focused closes the whole search overlay.
