### ISSUE TITLE
Conditional library load

### ISSUE THREAD

**Issue by mukrop** [faktaoklimatu/web-core#62]
Currently, all used libraries are loaded on all webpages. To optimize, it may be better to enable conditional load for example for LaTeX display library. Similar discussion may be relevant for the potential flag library (relevant for survey on net zero emissions).

**Comment by mgrabovsky** [comment]
For completeness, related discussion in faktaoklimatu/web-cz#835.

**Comment by ufonzak** [comment]
I wonder how much of a problem this is. As I currently checked the JS files are properly cached on the browser side. That means the initial load can be slower but subsequent loads are very fast. Are we trying to optimize the CPU time? For that, we should probably profile the page and identify if there is a case for optimization.

**Comment by mukrop** [comment]
Not much CPU time – I aimed at lower data traffic and fewer indirect queries. Especially for features we use only rarely (such as equations, country flags and similar).

* Do you think this is unnecessary premature optimization? (any opinions are welcome, @ufonzak, @mgrabovsky)
* If not, is there any simpler way to achieve this? (e.g. can the CSS/JS load be AJAX-lazy and query the resources only if the page asks to?)

**Comment by mgrabovsky** [comment]
I think it's unnecessary at the moment. I think what I'd really like the future would be _bundling_, i.e. just stuff all the JS (including relevant Bootstrap bits) into a single file, minify it and serve that. Same thing with CSS. Although that has its own drawbacks as well, of course.

**Comment by mukrop** [comment]
OK, I close this as premature optimization problem :-P.
We may reopen it later, if the necessity comes.
