### ISSUE TITLE
Weird spacing of text in narrow columns

### ISSUE THREAD

**Issue by setcz** [faktaoklimatu/web-core#63]
There are too wide spaces between words (due to a block alignment) if the column is too narrow. Infobox taking 2/3 of column width makes this more prominent. See example below:

![185645706_295543122046378_548517390192911908_n](https://user-images.githubusercontent.com/10813593/117962643-bfe8df80-b31f-11eb-9069-97b8f763bf45.jpeg)

**Comment by setcz** [comment]
Additional example:
<img width="566" alt="Screenshot 2021-05-12 at 12 51 28" src="https://user-images.githubusercontent.com/10813593/117963553-d0e62080-b320-11eb-93e3-6f3be3c6df84.png">

**Comment by mgrabovsky** [comment]
We should really drop justified alignment and just flush left everywhere. Justification makes little sense on web in general and it's especially pointless in absence of word-breaking/hyphenation.

**Comment by mukrop** [comment]
I'm probably against dropping the whole of it. But I see that (again)
something messed with the alignment with us not noticing – the mobile view
should have flush left, but does not.

>

**Comment by crysman** [comment]
Remember fighting this back in the old days when I had been building webs without frameworks... (as many [others](https://dmjcomputerservices.com/blog/why-you-shouldnt-align-html-justify/)) Now we've come to year 2021 and still troubling...

**Comment by jankrcal** [comment]
I would also prefer dropping it completely.

**Comment by mukrop** [comment]
Reopened in an actionable way in #112.
