### ISSUE TITLE
Add non-break space before footnote link?

### ISSUE THREAD

**Issue by setcz** [faktaoklimatu/web-core#64]
😿 
<img width="561" alt="Screenshot 2021-05-12 at 12 52 27" src="https://user-images.githubusercontent.com/10813593/117963854-2a4e4f80-b321-11eb-9fcd-6966d0485924.png">

**Comment by mgrabovsky** [comment]
I suppose we need a guideline for writing footnotes – there should be no space between the preceding token and the reference.

I fixed this in the previous explainer (on the relation of CO₂ concentration—heating), but didn't have the time to go through this one.

**Comment by mukrop** [comment]
Yes, please add that to the typography manual.
However, we need to fix display issues wen multiple footnotes are present. Technically, no space should be put in between the two footnote marks, but then they seem to be just one double-digit number (so the current workaround is adding an extra space).

PS: If anybody found time to investigate it, maybe a better UX footnotes would be the way WaitButWhy has them?
See e.g. https://waitbutwhy.com/2021/04/lanby.html (we already use similar UI for the glossary).

**Comment by mgrabovsky** [comment]
- [x] Problem in OP fixed in faktaoklimatu/web-cz#871.
- [x] Instructions added to the typography manual.

It'd be nice to separate consecutive links with a comma, for instance, automatically. Though I'm not sure if that's possible with pure CSS since it ignores “non-element nodes (such as text nodes and comments)”.

**Comment by mgrabovsky** [comment]
I'm closing this since the original issue has been resolved downstream.

Moving discussion regarding improvements to #100.
