### ISSUE TITLE
Error in glyph replacement plugin

### ISSUE THREAD

**Issue by mukrop** [faktaoklimatu/web-core#69]
If the page does not have a header (or has any other problem preventing it to have "output" defined), the glyph replacement plugin should not fail due to changes by @mgrabovsky.

However, with an empty page (no header), I get the following:

```
/mnt/d/repositories/fakta-2050podcast/_plugins/glyph-replacement-czech.rb:19:in `block (2 levels) in <top (required)>':
undefined local variable or method `continue' for main:Object (NameError)
```

**Comment by mgrabovsky** [comment]
Sorry about that—still rusty in Ruby.
