### ISSUE TITLE
Searching does not work well on Android (Chrome)

### ISSUE THREAD

**Issue by jankrcal** [faktaoklimatu/web-core#78]
Whenever the virtual keyboard appears disappears, the searchbox gets hidden.

This is particularly bad for the initial experience:
 - you tap on the search icon
 - the search box appears (and receives focus)
 - the virtual keyboard pops-up
 - the search box disappears
(luckily the virtual keyboard stays open which makes it possible to search by tapping the search icon again)

**Comment by jankrcal** [comment]
@katkolouchova Am I right you have an iPhone? Could you please test the same on iPhone / Safari (and potentially on iPhone / Chrome)?

**Comment by mgrabovsky** [comment]
This doesn't occur on Safari or Chrome on iPhone. It seems to affect Firefox on Android as well, though.

**Comment by jankrcal** [comment]
Thanks!

Oh, I've got it. That's an unintended side-effect of a previous hack :) Working on a fix.
