### ISSUE TITLE
jekyll-tidy likely broke search.json

### ISSUE THREAD

**Issue by jankrcal** [faktaoklimatu/web-core#81]
Search does not work on the web. The json (/search.json) does not parse in JS. It seems to be caused by newlines in the html snippets within the json.

Can you please disable the tool on the json?

**Comment by jankrcal** [comment]
(btw. it's about time to write some automated test for search, at least on the level of JS parses the json)

**Comment by mukrop** [comment]
Sorry for that, seems even testing of two people was not thorough enough. I always forget that the search may get broken :-/.

As a hot fix, I've disabled the tool. Setting the search JSON as an exception should not be a problem, though I leave that for @ufonzak with a second round of check, what files do we have in the build web for other possible exceptions (think of `robots.txt`, `sitemap.xml` and similar...). Check the `_site` folder that contains the generated Jekyll site.

**Comment by mukrop** [comment]
(And yes, we should definitely have some tests for search as it seems to be breakable :-P. Please add an issue on that.)

**Comment by ufonzak** [comment]
Sorry that I broke the search, I'll provide a pattern for the exclusion of all the files.

What sort of tests do you guys have in mind? (e.g. Karma or something closer to code?)
