### ISSUE TITLE
Support for language-specific (local) plugins

### ISSUE THREAD

**Issue by mgrabovsky** [faktaoklimatu/web-core#9]
The current set up requires that all plugins be placed in the upstream (core) repository and does not allow for enabling/disabling specific plugins downstream (in individual websites). Subsequently, all the plugins are active in downstream build, with no option to toggle only some of them.

Although the majority of the plugins so far are universal, [glyph-replacement.rb](https://github.com/faktaoklimatu/web-core/blob/d1fdb8b2e17c969e066ea2297056f41fd0a7a837/_plugins/glyph-replacement.rb) implements rules pertaining to non-breaking spaces that are specific to some languages (including Czech and Slovak) but not English, for instance.

If more such plugins were to appear, it would be beneficial either a) to allow for toggling some of the language-specific plugins via a configuration flag (preferred solution), or b) to allow for downstream to include their own (additional) plugins.

**Comment by mukrop** [comment]
I implemented the solution with local plugins. I find that (for now) better than stacking all language-specific plugins in the core repository. Though I admit we may decide to rewire this later on if we get much more plugins.
