### ISSUE TITLE
TOC should not be present when there's only one section

### ISSUE THREAD

**Issue by jankrcal** [faktaoklimatu/web-core#90]
This used to work before, not sure when it got broken.

When there's only one section in the document, TOC does not get generated (correctly) but the title of the TOC is still present (bug):

![Screen Shot 2021-06-15 at 12 20 13](https://user-images.githubusercontent.com/145227/122036610-0bd1ed00-cdd4-11eb-9abc-82b101ba1e03.png)

See https://faktaoklimatu.cz/infografiky/teplota-cr for an example.

**Comment by J08nY** [comment]
Likely culprit is a clash between the changes in 352fd4ec and 50257300.
